
# Configs for twilight.
# Please keep this in sync with config_loader.py

# The number of full tiles in the North-South span of the room
NUM_TILES_LENGTH: 15

# The number of full tiles in the East-West span of the room
NUM_TILES_WIDTH: 10

# The number of RGB LEDS on each strip.
NUM_LEDS_PER_STRIP: 140

# Safe amount of time (milis) between consecutive writes to the same unit.
RATE_LIMIT_TIME: 100

# TODO(wchill): write docstring for this.
SERIAL_RATE: 921600

DEBUG_MODE: false

# Details about Units.
UNITS:
  a:
    north_south: 9
    west_east: 6
    serial_port: '/dev/ttyACM0'
  b:
    north_south: 5
    west_east: 6
    serial_port: '/dev/ttyACM1'
  c:
    north_south: 5
    west_east: 2
    serial_port: '/dev/ttyACM2'

# Folder for holding plugins
PLUGINS_FOLDER: '/plugins/'

# Folder for holding filters
FILTERS_FOLDER: '/filters/'

# Default program length, in seconds
PLUGIN_CYCLE_LENGTH: 30
